name: Build

permissions:
  contents: write

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    name: Build Shared Library
    runs-on: ubuntu-latest
    container:
      image: pytorch/manylinux2_28-builder:cuda11.8

    # see https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Environments
        run: |
          echo "PYTHON_VERSION=$(python3 -c "from os import environ as env; print({'3.7': 'cp37-cp37m', '3.8': 'cp38-cp38', '3.9': 'cp39-cp39', '3.10': 'cp310-cp310', '3.11': 'cp311-cp311', '3.12': 'cp312-cp312' }['${{ matrix.python-version }}'])")" >> $GITHUB_ENV
          echo "PATH=$PATH" >> $GITHUB_ENV

      - name: Set up Packages
        env:
          PYBIN: /opt/python/${{ env.PYTHON_VERSION }}/bin
        run: |
          yum install -y pigz clang-tools-extra openmpi openmpi-devel spdlog spdlog-devel libibverbs rdma-core-devel numactl numactl-devel numactl-libs
          pwd && ls -la
          sed -i '256d' 3rdparty/mscclpp/src/bootstrap/bootstrap.cc
          cat 3rdparty/patches/spdlog/*.patch | patch -p1 -d 3rdparty/spdlog
          $PYBIN/pip install cmake mypy pybind11 black
          cd pipeline/src/generate-gemm && $PYBIN/python genGEMM.py && cd ../../
      
      - name: Build Library
        env:
          PATH: ${{ env.PATH }}:/usr/lib64/openmpi/bin
          PYBIN: /opt/python/${{ env.PYTHON_VERSION }}/bin
          PREFIX: /opt/python/${{ env.PYTHON_VERSION }};/usr/lib64/openmpi
          pybind11_DIR: /opt/python/${{ env.PYTHON_VERSION }}/lib/python${{ matrix.python-version }}/site-packages/pybind11
          CUDACXX: "/usr/local/cuda-11.8/bin/nvcc"
          CUDA_HOME: "/usr/local/cuda-11.8"
          CFLAGS: "-I/usr/include" 
          LDFLAGS: "-L/usr/lib"
        run: |
          cd pipeline && mkdir -p build && cd build
          which cmake && cmake --version
          which mpicxx && mpicxx --version
          ${PYBIN}/cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=${PREFIX} -DBUILD_PYTHON_BINDINGS=OFF -DBYPASS_GPU_CHECK=ON -DUSE_CUDA=ON ..
          make -j$(nproc)
          ls -la
      
      - uses: actions/upload-artifact@v4
        with:
          name: nanoflow
          path: pipeline/build
